services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app/static/uploads:/app/app/static/uploads
      - ./models:/app/models
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key
      - PORT=5000
    restart: unless-stopped
